#!/usr/bin/env python

#:vim: set syn=python

import sys
import re
import Levenshtein
import icalendar
import getopt


class ICSMerger():
    o = ""
    def ICSMerger(self):
        pass
    def add_ics(self, stri):
        self.o = self.o + stri
    def merge(self):
        return self.o

def usage():
    print "icsmerge -o outfile infile1 infile2 ... infileN"

def main(argv):
    outfile = ""
    try:
        opts, inputfiles = getopt.getopt(argv, "vho:", "")
        for opt, arg in opts:
            if opt in ("-v"):
                print "icsmerge version 0"
                sys.exit()
            elif opt in ("-o"):
                outfile = arg
            elif opt in ("-h"):
                usage()
                sys.exit()
    except getopt.GetoptError as err:
        print "Option error: %s" % err
        usage()
        sys.exit(1)

    if len(outfile) > 0:
        try:
            oh = open(outfile, "wb")
        except IOError as err:
            print "could not open output file %s: %s" % (outfile, err)
            sys.exit(1)

    else:
        oh = sys.stdout

    merger = ICSMerger()

    for f in inputfiles:
        try:
            merger.add_ics("".join(open(f,"r").readlines()))
        except Exception as err:
            print "could not read input file %s: %s" % (f, err)

    output =  merger.merge()
    oh.write(output)
# do stuff


# close
    oh.close()


if __name__ == "__main__":
        main(sys.argv[1:]) # [1:] slices off the first argument which is the name of the program

